### ISSUE TITLE
Creating an array parameter fails

### ISSUE THREAD

**Issue by nullproxy** [kusanagi/katana-sdk-php7#35]
When defining a parameter as an *array* using `Request::newParam()` I got an error stating that the data type must be a *string*, yet I'm defining an *array* in PHP.

In my case, I'm defining an *array* where each item is an *array*, for example:

```php
$param = $request->newParam('params', [['a', 'b', 'c'], ['d', 'e', 'f']], 'array');
```

Here is the error message received:

```
Callback error: Language error (shutdown) (1) Uncaught TypeError: Argument 2 passed to Katana\Sdk\Api\ServiceCall::newParam() must be of the type string, array given, called in /vendor/kusanagi/katana-sdk-php7/src/Api/RequestApi.php on line 270 and defined in /vendor/kusanagi/katana-sdk-php7/src/Api/ParamAccessorTrait.php:74
Stack trace:
#0 /vendor/kusanagi/katana-sdk-php7/src/Api/RequestApi.php(270): Katana\Sdk\Api\ServiceCall->newParam('params', Array, 'array')
#1 /middleware.php(45): Katana\Sdk\Api\RequestApi->newParam('params', Array, 'array')
#2 /vendor/kusanagi/katana-sdk-php7/src/Executor/AbstractExecutor.php(77): {closure}(Object(Katana\Sdk\Api\RequestApi))
#3 /vendor/kusanagi/katana-sdk-php7/src/Executor/ZeroMqLoopExecutor.php(138): 
```

The issue appears to come from here:

https://github.com/kusanagi/katana-sdk-php7/blob/master/src/Api/ParamAccessorTrait.php#L76

This was using version **1.1.4** of the framework, with system info below:

```
Linux work 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fcastilloes** [comment]
That was fixed for *1.0.5*: https://github.com/kusanagi/katana-sdk-php7/commit/83a46928be1dc5530a2aa31d6959c032d2efa391

Can you double check your SDK version?

**Comment by nullproxy** [comment]
The required dependency is "kusanagi/katana-sdk-php7", with the version constraint set as "^1.1".

When running `composer show` it gives the following:

```
kusanagi/katana-sdk-php7 1.1.x-dev f098bc2
```

Which corresponds the the latest commit on the [1.1](https://github.com/kusanagi/katana-sdk-php7/commits/1.1) branch.

**Comment by fcastilloes** [comment]
Version branches was not being updated. Merged now.

**Comment by nullproxy** [comment]
I now get the following:

```
Invalid parameter for action "call" on Service "proxy" (1.0.0): "params"
```

The configuration for the `param` is the following:

```xml
<param name="params" type="array" required="true"/>
```

And the definition of the `Param` is as defined before:

```php
$param = $request->newParam('params', [['a', 'b', 'c'], ['d', 'e', 'f']], 'array');
```

**Comment by jeronimoalbi** [comment]
@jameswatts can you try adding `array-format="multi"` to the `param` definition. By default `array-format` is "csv" and you are sending a "multi" array.

**Comment by fcastilloes** [comment]
I've done a couple tests with an array param set from the request middleware and I think the issue is in the framework, not in the SDK.

I got an action with this config (removing the irrelevant for brevity):

```yaml
action:
  - name: list
    param:
      - name: ids
        type: array
        http-gateway: false
```

Then I did a test with a simple array and logging both the message sent to the framework and the result from the SDK:

```php
$param = $request->newParam('ids', ['a', 'b', 'c'], 'array');
```

The message looks correct.

```json
{
  "cr": {
    "n": "rest",
    "r": {
      "c": {
        "s": "orgs",
        "v": "1.1.0-qa.5",
        "a": "list",
        "p": [
          {
            "n": "ids",
            "v": [
              "a",
              "b",
              "c"
            ],
            "t": "array"
          }
        ]
      }
    }
  }
}
```

But the log does not match:

```
2017-08-31T17:58:43.919Z [DEBUG] [SDK] ["a"]
```

Then repeated the test with a multi array, with this other code:

```php
$param = $request->newParam('ids', [['a', 'b', 'c'], ['d', 'e', 'f']], 'array');
```

Once again, the message looks good.

```json
{
  "cr": {
    "n": "rest",
    "r": {
      "c": {
        "s": "orgs",
        "v": "1.1.0-qa.5",
        "a": "list",
        "p": [
          {
            "n": "ids",
            "v": [
              [
                "a",
                "b",
                "c"
              ],
              [
                "d",
                "e",
                "f"
              ]
            ],
            "t": "array"
          }
        ]
      }
    }
  }
}
```

But now I get the same error mentioned in the comment above.

```
Invalid parameter for action "list" on Service "orgs" (1.1.0-qa.5): "ids"
```

Then, trying with `array-multi` as suggested @jeronimoalbi solves both tests.

```
2017-08-31T18:09:41.727Z [DEBUG] [SDK] [["a","b","c"],["d","e","f"]]
```

```
2017-08-31T18:10:40.136Z [DEBUG] [SDK] ["a","b","c"]
```

I think there might be something wrong with the arrays in the framework here, but I can see no issue in the SDK.
